# Default rules
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# Izinkan ThingsBoard app container
host    thingsboard     postgres        all                     trust

# Izinkan Server backup (pakai /24 untuk cover semua kemungkinan IP)
host    replication     replicator      192.168.35.0/24         md5
host    thingsboard     replicator      192.168.35.0/24         md5
host    replication     replicator      192.168.20.0/24         md5
host    thingsboard     replicator      192.168.20.0/24         md5
